### ISSUE TITLE
ValueError: grch38_to_grch37_ref_chain path not found: gs://hail-common/references/grch38_to_grch37.over.chain.gz

### ISSUE THREAD

**Issue by barslmn** [broadinstitute/seqr-loading-pipelines#623] opened 2023-11-18 19:16 UTC
Hi,
I have a local seqr installation and trying to load the data locally without gcloud. I have followed the manual installation document linked in seqr repo and have docker containers. 

I'm trying to load data using the following command:

```
docker-compose exec pipeline-runner load_data.sh 37 WES demo demo.vcf.gz
```

However, it is giving the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/seqr-loading-pipelines/luigi_pipeline/seqr_loading.py", line 89, in run
    if self.grch38_to_grch37_ref_chain: check_if_path_exists(self.grch38_to_grch37_ref_chain, "grch38_to_grch37_ref_chain")
  File "/seqr-loading-pipelines/luigi_pipeline/seqr_loading.py", line 23, in check_if_path_exists
    raise ValueError(f"{label} path not found: {path}")
ValueError: grch38_to_grch37_ref_chain path not found: gs://hail-common/references/grch38_to_grch37.over.chain.gz
```

This is [set to a bucket link as default here](https://github.com/barslmn/seqr-loading-pipelines/blob/7db47b2c0bbe01398f768888a5ef18aff8b9542e/luigi_pipeline/seqr_loading.py#L62).
But tries  [check_if_path_exists](https://github.com/barslmn/seqr-loading-pipelines/blob/7db47b2c0bbe01398f768888a5ef18aff8b9542e/luigi_pipeline/seqr_loading.py#L35)  [here](https://github.com/barslmn/seqr-loading-pipelines/blob/7db47b2c0bbe01398f768888a5ef18aff8b9542e/luigi_pipeline/seqr_loading.py#L85)  instead of [check_if_file_exists](https://github.com/barslmn/seqr-loading-pipelines/blob/7db47b2c0bbe01398f768888a5ef18aff8b9542e/luigi_pipeline/seqr_loading.py#L30).

It is not downloaded to local data folder when [download_reference_data](https://github.com/barslmn/seqr-loading-pipelines/blob/main/docker/bin/download_reference_data.sh) is run.

Looking at the file on the container the function is different and the check_if_file_exists function doesn't exist.

**Comment by bpblanken** [comment] 2023-11-20 17:34
Hi @barslmn!

Thanks for reporting this bug!  I know that the `check_if_file_exists` logic has changed a bit over the past six months, so we should make sure you're running on an up-to-date version of the code.  

We don't download that file, and instead use it directly from cloud storage.  Are you able to access `gs://hail-common/references/grch38_to_grch37.over.chain.gz` with `gsutil` or `gcloud storage ls`?

**Comment by barslmn** [comment] 2023-11-20 19:28
Hi Benjamin,

I did a quick fix on the container and added to does_file_exist function and change the [check_if_path_exists function call ](https://github.com/barslmn/seqr-loading-pipelines/blob/7db47b2c0bbe01398f768888a5ef18aff8b9542e/luigi_pipeline/seqr_loading.py#L85C45-L85C65) to does_file_exist and it passed that step without a problem.

However later in pipe I got this error:

```
Traceback (most recent call last):                                                                                                                
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run                                                                 
    new_deps = self._run_get_new_deps()                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps                                                   
    task_gen = self.task.run()                                                                                                                    
  File "/seqr-loading-pipelines/luigi_pipeline/seqr_loading.py", line 97, in run                                                                  
    self.read_input_write_mt()                                                                                                                    
  File "/seqr-loading-pipelines/luigi_pipeline/seqr_loading.py", line 127, in read_input_write_mt                                                 
    self.validate_mt(mt, self.genome_version, self.sample_type)                                                                                   
  File "/seqr-loading-pipelines/luigi_pipeline/seqr_loading.py", line 179, in validate_mt                                                         
    sample_type_stats = HailMatrixTableTask.sample_type_stats(mt, genome_version)                                                                 
  File "/seqr-loading-pipelines/luigi_pipeline/lib/hail_tasks.py", line 109, in sample_type_stats                                                 
    ht = hl.read_table(ht_path)                                                                                                                   
  File "<decorator-gen-1408>", line 2, in read_table                                                                                              
  File "/usr/local/lib/python3.7/site-packages/hail/typecheck/check.py", line 577, in wrapper                                                     
    return __original_func(*args_, **kwargs_)                                                                                                     
  File "/usr/local/lib/python3.7/site-packages/hail/methods/impex.py", line 2925, in read_table
    for rg_config in Env.backend().load_references_from_dataset(path):
  File "/usr/local/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 337, in load_references_from_dataset
    return json.loads(self.hail_package().variant.ReferenceGenome.fromHailDataset(self.fs._jfs, path))
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.7/site-packages/hail/backend/py4j_backend.py", line 31, in deco
    raise fatal_error_from_java_error_triplet(deepest, full, error_id) from None
hail.utils.java.FatalError: HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht

Java stack trace:                                                                                                                                 
is.hail.utils.HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/       
        at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:17)                                                                              
        at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:17)                                                                             
        at is.hail.utils.package$.fatal(package.scala:78)                                                                                         
        at is.hail.expr.ir.RelationalSpec$.readMetadata(AbstractMatrixTableSpec.scala:33)                                                         
        at is.hail.expr.ir.RelationalSpec$.readReferences(AbstractMatrixTableSpec.scala:74)                                                       
        at is.hail.variant.ReferenceGenome$.fromHailDataset(ReferenceGenome.scala:581)                                                            
        at is.hail.variant.ReferenceGenome.fromHailDataset(ReferenceGenome.scala)                                                                 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                            
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                          
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                  
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                       
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)                                                                           
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)                                                                     
        at py4j.Gateway.invoke(Gateway.java:282)                                                                                                  
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)                                                                   
        at py4j.commands.CallCommand.execute(CallCommand.java:79)                                                                                 
        at py4j.GatewayConnection.run(GatewayConnection.java:238)                                                                                 
        at java.lang.Thread.run(Thread.java:750)
```

I can access to this directory inside container:

```
4f63a4ef64d5:/seqr-loading-pipelines]$ gsutil ls gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/README.txt
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/_SUCCESS
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/metadata.json.gz
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/globals/
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/references/
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/rows/
```

**Comment by bpblanken** [comment] 2023-11-20 20:41
hrm... ok.  Are you able to access with hail itself?

```
bblanken@wmbbe-67c luigi_pipeline % python3
Python 3.8.10 (default, Feb 13 2023, 14:19:03)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hail as hl
>>> ht = hl.read_table('gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht')
```

FWIW I'm going to start looking at https://github.com/broadinstitute/seqr-loading-pipelines/issues/624.  I think the docker  image itself is just out of date with our codebase, so helping get things back in buildable state should help clarify things a bit.

**Comment by barslmn** [comment] 2023-11-20 22:48
Trying to access using hail reproduces the error:

```
4f63a4ef64d5:/seqr-loading-pipelines]$ python3                                                                                                    
Python 3.7.1 (default, Nov 16 2022, 17:30:35)                                                                                                     
[GCC 6.3.0 20170516] on linux                                                                                                                     
Type "help", "copyright", "credits" or "license" for more information.                                                                            
>>> import hail as hl                                                                                                                             
>>> ht = hl.read_table('gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht')                                         
Initializing Hail with default parameters...                                                                                                      
2023-11-20 21:50:25.220 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where app
licable                                                                                                                                           
Setting default log level to "WARN".                                                                                                              
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).                                                      
Running on Apache Spark version 3.1.3                                                                                                             
SparkUI available at http://4f63a4ef64d5:4040                                                                                                     
Welcome to                                                                                                                                        
     __  __     <>__                                                                                                                              
    / /_/ /__  __/ /                                                                                                                              
   / __  / _ `/ / /                                                                                                                               
  /_/ /_/\_,_/_/_/   version 0.2.105-acd89e80c345                                                                                                 
LOGGING: writing to /seqr-loading-pipelines/hail-20231120-2150-0.2.105-acd89e80c345.log                                                           
Traceback (most recent call last):                                                                                                                
  File "<stdin>", line 1, in <module>                                                                                                             
  File "<decorator-gen-1408>", line 2, in read_table                                                                                              
  File "/usr/local/lib/python3.7/site-packages/hail/typecheck/check.py", line 577, in wrapper                                                     
    return __original_func(*args_, **kwargs_)                                                                                                     
  File "/usr/local/lib/python3.7/site-packages/hail/methods/impex.py", line 2925, in read_table                                                   
    for rg_config in Env.backend().load_references_from_dataset(path):                                                                            
  File "/usr/local/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 337, in load_references_from_dataset                          
    return json.loads(self.hail_package().variant.ReferenceGenome.fromHailDataset(self.fs._jfs, path))                                            
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__                                                      
    answer, self.gateway_client, self.target_id, self.name)                                                                                       
  File "/usr/local/lib/python3.7/site-packages/hail/backend/py4j_backend.py", line 31, in deco
    raise fatal_error_from_java_error_triplet(deepest, full, error_id) from None
hail.utils.java.FatalError: HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht

Java stack trace:
is.hail.utils.HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht
        at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:17)
        at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:17)
        at is.hail.utils.package$.fatal(package.scala:78)
        at is.hail.expr.ir.RelationalSpec$.readMetadata(AbstractMatrixTableSpec.scala:33)
        at is.hail.expr.ir.RelationalSpec$.readReferences(AbstractMatrixTableSpec.scala:74)
        at is.hail.variant.ReferenceGenome$.fromHailDataset(ReferenceGenome.scala:581)
        at is.hail.variant.ReferenceGenome.fromHailDataset(ReferenceGenome.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:750)



Hail version: 0.2.105-acd89e80c345
Error summary: HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht
```



About #624, I got the container builded with that patch but same error continues:


```
833bd8222448:/]$ python3
Python 3.9.17 (main, Nov 17 2023, 21:52:31)                                                                                                       
[GCC 12.2.0] on linux                                                                                                                             
Type "help", "copyright", "credits" or "license" for more information.                                                                            
>>> import hail as hl                                                                                                                             
>>> ht = hl.read_table('gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht')                                         
Initializing Hail with default parameters...                                                                                                      
SLF4J: No SLF4J providers were found.                                                                                                             
SLF4J: Defaulting to no-operation (NOP) logger implementation                                                                                     
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.                                                                      
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.                                                          
SLF4J: Ignoring binding found at [jar:file:/usr/local/lib/python3.9/site-packages/pyspark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticL
oggerBinder.class]                                                                                                                                
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.                                                                   
Setting default log level to "WARN".                                                                                                              
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).                                                      
Traceback (most recent call last):                                                                                                                
  File "<stdin>", line 1, in <module>                                                                                                             
  File "<decorator-gen-1458>", line 2, in read_table                                                                                              
  File "/usr/local/lib/python3.9/site-packages/hail/typecheck/check.py", line 584, in wrapper                                                     
    return __original_func(*args_, **kwargs_)                                                                                                     
  File "/usr/local/lib/python3.9/site-packages/hail/methods/impex.py", line 3049, in read_table                                                   
    for rg_config in Env.backend().load_references_from_dataset(path):                                                                            
  File "/usr/local/lib/python3.9/site-packages/hail/utils/java.py", line 88, in backend                                                           
    return Env.hc()._backend                                                                                                                      
  File "/usr/local/lib/python3.9/site-packages/hail/utils/java.py", line 66, in hc                                                                
    init()                                                                                                                                        
  File "<decorator-gen-1768>", line 2, in init                                                                                                    
  File "/usr/local/lib/python3.9/site-packages/hail/typecheck/check.py", line 584, in wrapper                                                     
    return __original_func(*args_, **kwargs_)                                                                                                     
  File "/usr/local/lib/python3.9/site-packages/hail/context.py", line 349, in init                                                                
    return init_spark(
  File "<decorator-gen-1770>", line 2, in init_spark
  File "/usr/local/lib/python3.9/site-packages/hail/typecheck/check.py", line 584, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/usr/local/lib/python3.9/site-packages/hail/context.py", line 428, in init_spark
    backend = SparkBackend(
  File "/usr/local/lib/python3.9/site-packages/hail/backend/spark_backend.py", line 211, in __init__
    self._jhc = hail_package.HailContext.apply(
  File "/usr/local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value( 
  File "/usr/local/lib/python3.9/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling z:is.hail.HailContext.apply.
: is.hail.utils.HailException: Hail requires Java 8 or 11, found 17.0.9
        at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:17)
        at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:17)
        at is.hail.utils.package$.fatal(package.scala:78)
        at is.hail.HailContext$.checkJavaVersion(HailContext.scala:87)
        at is.hail.HailContext$.apply(HailContext.scala:112)
        at is.hail.HailContext.apply(HailContext.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:840)

>>> hl.__version__
'0.2.115-10932c754edb'

```

I am suspecting, it could be related to gcs-connector.

**Comment by bpblanken** [comment] 2023-11-21 00:10
You should't have to authenticate, as those files are public.  It looks like we're running into the `java17 vs java11/java8 hail dependency` issue that you've noticed and mentioned.  

One quick suggestion while I try to help fix that issue is to try using our latest published image at our public repository here: `gcr.io/seqr-project/pipeline-runner:gcloud-prod`.  The code there is out of date, but the image should be functional and will load just fine into seqr.

**Comment by barslmn** [comment] 2023-11-21 01:56
Sorry for the confusion, I am trying both of the images. [first error](https://github.com/broadinstitute/seqr-loading-pipelines/issues/623#issuecomment-1819930141) is from the latest image at `gcr.io/seqr-project/pipeline-runner:gcloud-prod`. Second one is from the image I rebuild. The newly build image also gives the same error after installing the jdk-11.

**Newer test image pipeline-runner:bar**
```
Hail version: 0.2.115-10932c754edb                                                                                                                
Error summary: HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht       
>>> >>>                                                                                                                                           
>>> import hail as hl                                                                                                                             
ht = hl.read_table('gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht')                                             
>>> Traceback (most recent call last):                                                                                                            
  File "<stdin>", line 1, in <module>                                                                                                             
  File "<decorator-gen-1458>", line 2, in read_table                                                                                              
  File "/usr/local/lib/python3.9/site-packages/hail/typecheck/check.py", line 584, in wrapper                                                     
    return __original_func(*args_, **kwargs_)                                                                                                     
  File "/usr/local/lib/python3.9/site-packages/hail/methods/impex.py", line 3049, in read_table                                                   
    for rg_config in Env.backend().load_references_from_dataset(path):                                                                            
  File "/usr/local/lib/python3.9/site-packages/hail/backend/py4j_backend.py", line 118, in load_references_from_dataset                           
    return json.loads(self._jbackend.pyLoadReferencesFromDataset(path))                                                                           
  File "/usr/local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1321, in __call__                                                      
    return_value = get_return_value(                                     
  File "/usr/local/lib/python3.9/site-packages/hail/backend/py4j_backend.py", line 35, in deco                                                    
    raise fatal_error_from_java_error_triplet(deepest, full, error_id) from None                                                                  
hail.utils.java.FatalError: HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grc
h37.ht                                                                                                                                            
                                                                                                                                                  
Java stack trace:
is.hail.utils.HailException: No file or directory found at gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht
        at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:17)
        at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:17)
        at is.hail.utils.package$.fatal(package.scala:78)
        at is.hail.expr.ir.RelationalSpec$.readMetadata(AbstractMatrixTableSpec.scala:33)
        at is.hail.expr.ir.RelationalSpec$.readReferences(AbstractMatrixTableSpec.scala:69)
        at is.hail.variant.ReferenceGenome$.fromHailDataset(ReferenceGenome.scala:560)
        at is.hail.backend.spark.SparkBackend.pyLoadReferencesFromDataset(SparkBackend.scala:618)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
```

**Comment by bpblanken** [comment] 2023-11-21 02:39
Can you maybe try installing the storage connector via the recommended hail path (and not the way the docker file is doing it) with:

```
curl -sSL https://broad.io/install-gcs-connector | python3
```

I'm able to reproduce locally and this fixes the `hl.read_table` at least.

**Comment by bpblanken** [comment] 2023-11-21 02:45
One other suggestion

```
google auth application-default login
``` 

needs to be run _inside_ the container (per the [docs](https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md?plain=1#L68)).  `gcloud auth login` will place your credentials somewhere spark cannot find them.

**Comment by barslmn** [comment] 2023-11-22 10:39
I did some more digging using the latest image.
We have to auth with `gcloud auth application-default login` from inside the container for accessing files in buckets.



There is also a warning/error abot ps which only shows when hail for initialize:

```
>>> hl.hadoop_exists("gs://hail-common/references/grch38_to_grch37.over.chain.gz")
Initializing Hail with default parameters...
/usr/local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/usr/local/lib/python3.10/site-packages/pyspark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Running on Apache Spark version 3.3.2
SparkUI available at http://aa1e7731b582:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.122-be9d88a80695
LOGGING: writing to /hail-20231122-1034-0.2.122-be9d88a80695.log
True
```

That goes away with `apt install procps`

**Comment by barslmn** [comment] 2023-11-22 13:06
I opened the PR. https://github.com/broadinstitute/seqr-loading-pipelines/pull/632

**Comment by bpblanken** [comment] 2023-11-22 14:51
I'm going to close this one.  For this:

```
I suggest it would be better to download these files for local deployment. Seqr already downloads like ~300Gb of data.

This can be labeled as feature request or enhancement I think.
```

I think we won't be able to make this particular change at the moment as we're working on a broader revision to the entire loading process for on-prem deployments that has already accounted for treating these validation tables similarly to the rest of the reference data.

**Closed by bpblanken** 2023-11-22 14:51 UTC

**Comment by barslmn** [comment] 2023-11-22 15:18
Good to hear.
Yes we can close this only thing required after the new commits is just authenticating. I created [a pr on seqr repo](https://github.com/broadinstitute/seqr/pull/3744).
